import Link from "next/link";
import { requireOwner } from "@/lib/auth/owner";
import { saveBusiness,saveSection,addSection,removeSection,moveSection,publishPage,setPageActive,createBranch } from "../actions";
import { sectionKinds } from "@/lib/content";

const labels:Record<string,string>={hero:"الرئيسية",about:"عن النشاط",hours:"مواعيد العمل",contact:"التواصل والموقع",social:"الشبكات الاجتماعية",payments:"طرق الدفع",links:"روابط إضافية",services:"الخدمات",gallery:"معرض الصور",reviews:"التقييمات",branch:"الفروع"};
export default async function EditBusiness({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string>>}) {
 const {id}=await params,query=await searchParams,{supabase}=await requireOwner();
 const {data:business,error}=await supabase.from("businesses").select("id,name,category,status").eq("id",id).single();
 if(error||!business)return <div className="form-card"><h1>النشاط غير موجود</h1><Link href="/admin">العودة للوحة</Link></div>;
 const {data:pages}=await supabase.from("business_pages").select("*").eq("business_id",id).order("page_type");
 const page=(pages||[]).find((p:any)=>p.page_type==="main")||pages?.[0];
 const {data:sections}=page?await supabase.from("page_sections").select("*").eq("page_id",page.id).order("position"):{data:[]};
 if(!page)return <div className="form-card">لا توجد صفحة لهذا النشاط.</div>;
 return <><div className="admin-title"><div><span className="eyebrow">{business.category}</span><h1>إدارة {business.name}</h1></div><div className="inline"><Link className="button secondary" href={"/b/"+page.slug} target="_blank">فتح الصفحة العامة</Link><Link className="button secondary" href={"/admin/cards?business="+id}>بطاقات النشاط</Link></div></div>
 {query.error&&<div className="alert">تعذر إتمام العملية: {decodeURIComponent(query.error)}</div>}{query.published&&<div className="alert">تم نشر نسخة جديدة من الصفحة.</div>}
 <form className="form-card" action={saveBusiness}><h2>بيانات الصفحة</h2><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><div className="form-grid"><label className="field">اسم النشاط<input name="name" defaultValue={business.name} maxLength={120} required/></label><label className="field">التصنيف<input name="category" defaultValue={business.category} maxLength={80}/></label><label className="field">رابط الصفحة<input name="slug" dir="ltr" defaultValue={page.slug} required pattern="[a-z0-9][a-z0-9-]{1,58}[a-z0-9]"/></label><label className="field">القالب<select name="template" defaultValue={page.template}><option value="cafe">مقهى ومطعم</option><option value="retail">متجر وخدمات</option><option value="professional">بسيط واحترافي</option></select></label></div><label className="inline"><input type="checkbox" name="archive" defaultChecked={business.status==="archived"}/> أرشفة النشاط وإخفاء صفحاته وبطاقاته</label><p><button className="button secondary">حفظ بيانات النشاط</button></p></form>
 <div className="form-card"><div className="admin-title"><div><h2>محرر الأقسام</h2><p className="muted">عدّل البيانات بصيغة JSON آمنة. لا يُنشر أي تغيير قبل الضغط على «نشر».</p></div><div className="inline"><Link className="button secondary" href={"/admin/businesses/"+id+"/preview?page="+page.id} target="_blank">معاينة المسودة</Link><form action={publishPage}><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><button className="button gold">نشر التغييرات</button></form></div></div>
 {(sections||[]).map((s:any,index:number)=><details className="editor-section" key={s.id} open={index===0}><summary className="inline"><strong>{labels[s.kind]||s.kind} · {s.title}</strong><span className={"pill "+(s.enabled?"green":"")}>{s.enabled?"ظاهر":"مخفي"}</span><span className="muted">ترتيب {index+1}</span></summary><form action={saveSection}><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="section_id" value={s.id}/><div className="form-grid"><label className="field">عنوان القسم<input name="title" defaultValue={s.title} maxLength={80}/></label><label className="field">نوع المحتوى<select name="kind" defaultValue={s.kind}>{sectionKinds.map(k=><option value={k} key={k}>{labels[k]||k}</option>)}</select></label></div><label className="field">المحتوى (JSON)<textarea name="content" defaultValue={JSON.stringify(s.content,null,2)} dir="ltr" spellCheck={false}/><small>استخدم عناصر JSON بعناوين وروابط آمنة فقط.</small></label><label className="inline"><input type="checkbox" name="enabled" defaultChecked={s.enabled}/> إظهار القسم</label><div className="inline" style={{marginTop:12}}><button className="button secondary">حفظ القسم</button></div></form><div className="inline" style={{marginTop:8}}><form action={moveSection}><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="section_id" value={s.id}/><input type="hidden" name="direction" value="up"/><button className="small-button" aria-label="تحريك للأعلى">↑ للأعلى</button></form><form action={moveSection}><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="section_id" value={s.id}/><input type="hidden" name="direction" value="down"/><button className="small-button" aria-label="تحريك للأسفل">↓ للأسفل</button></form><form action={removeSection}><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="section_id" value={s.id}/><button className="small-button danger">حذف</button></form></div></details>)}
 <form action={addSection} className="inline" style={{marginTop:18}}><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><select name="new_kind">{sectionKinds.map(k=><option value={k} key={k}>{labels[k]||k}</option>)}</select><button className="button secondary">إضافة قسم</button></form>
 </div>
 <form action={setPageActive} className="form-card inline"><input type="hidden" name="business_id" value={id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="active" value={page.is_active?"false":"true"}/><span>حالة الصفحة: <span className={"pill "+(page.is_active?"green":"red")}>{page.is_active?"منشورة ونشطة":"متوقفة"}</span></span><button className="button secondary">{page.is_active?"إيقاف الظهور":"تفعيل الصفحة"}</button></form>
 <form action={createBranch} className="form-card"><h2>إضافة فرع</h2><input type="hidden" name="business_id" value={id}/><input type="hidden" name="parent_page_id" value={page.id}/><div className="form-grid"><label className="field">اسم الفرع<input name="branch_name" required maxLength={100}/></label><label className="field">رابط الفرع<input name="slug" required dir="ltr" pattern="[a-z0-9][a-z0-9-]{1,58}[a-z0-9]"/></label></div><button className="button secondary">إنشاء صفحة فرع</button>{(pages||[]).filter((p:any)=>p.page_type==="branch").map((p:any)=><p key={p.id}><Link href={"/admin/businesses/"+id+"/preview?page="+p.id}>{p.branch_name} · /b/{p.slug}</Link></p>)}</form></>;
}