import { test } from "@e2e-dev/web";
import { credentials, expect } from "e2e";
import sharp from "sharp";

test("managed images survive upload, draft reload and publication, with pending-work guards", async ({ app, screen, browser }) => {
  test.skip(process.env.E2E_ALLOW_MUTATIONS !== "true", "Requires an isolated mutation-enabled project");
  await app.open("/login");
  await screen.getByLabel("البريد الإلكتروني").fill(credentials.user("owner").username);
  await screen.getByLabel("كلمة المرور").fill(credentials.user("owner").password);
  await screen.getByRole("button", "دخول آمن").tap();
  await expect(browser).toHaveURL(/\/admin(?:\?.*)?$/);
  const slug = `media-qa-${Date.now().toString(36)}`;
  await app.open("/admin/businesses/new");
  await screen.getByLabel("اسم النشاط").fill("Media QA illustrative fixture");
  await screen.getByLabel("التصنيف").fill("QA");
  await screen.getByLabel("رابط الصفحة").fill(slug);
  await browser.locator('input[name="template"][value="professional"]').check();
  await screen.getByRole("button", "إنشاء النشاط والصفحة").tap();
  await expect(browser).toHaveURL(/\/admin\/businesses\/[0-9a-f-]+\?created=1/);
  const path = await browser.evaluate(() => location.pathname);
  const png = (await sharp({ create: { width: 900, height: 450, channels: 4, background: { r: 40, g: 90, b: 140, alpha: 0.4 } } }).png().toBuffer()).toString("base64");
  const chooseFile = async (label: string, corrupt = false) => {
    await browser.evaluate(({ label, png, corrupt }) => {
      const input = Array.from(document.querySelectorAll<HTMLInputElement>('input[type="file"]')).find(input => input.closest("label")?.textContent?.includes(label))!;
      const dt = new DataTransfer(); dt.items.add(new File([corrupt ? "invalid" : Uint8Array.from(atob(png), c => c.charCodeAt(0))], "fixture.png", { type: "image/png" }));
      input.files = dt.files; input.dispatchEvent(new Event("change", { bubbles: true }));
      return null;
    }, { label, png, corrupt });
  };
  await screen.getByLabel("Hero image alt text").fill("Illustrative cover");
  await chooseFile("Upload hero image", true);
  await expect(browser.locator('.image-field [role="alert"]')).toContainText("could not be decoded");
  let releaseUpload: () => void = () => {};
  const uploadGate = new Promise<void>(resolve => releaseUpload = resolve);
  await browser.route("**/api/admin/media", async route => { await uploadGate; await route.continue(); });
  await chooseFile("Upload hero image");
  await expect(screen.getByRole("button", "Save draft")).toBeDisabled();
  await expect(screen.getByRole("button", "Publish", { exact: true })).toBeDisabled();
  releaseUpload();
  await expect(screen.getByLabel("Hero image URL")).toHaveValue(/business-media\/.*\.webp/);
  await browser.unroute("**/api/admin/media");
  const coverUrl = await browser.evaluate(() => (document.querySelector('.image-field input[dir="ltr"]') as HTMLInputElement).value);
  await screen.getByLabel("Logo image alt text").fill("Transparent fixture logo");
  await chooseFile("Upload logo image");
  await expect(screen.getByLabel("Logo image URL")).toHaveValue(/business-media\/.*\.webp/);
  await screen.getByRole("button", "Save draft").tap();
  await expect(browser.locator(".editor-save-status")).toHaveText("Draft saved");
  await app.open(path);
  await expect(screen.getByLabel("Hero image URL")).toHaveValue(coverUrl);
  await expect(screen.getByLabel("Hero image alt text")).toHaveValue("Illustrative cover");
  await screen.getByRole("button", /Find us/).tap();
  await screen.getByLabel("Address").fill("Illustrative Cairo address");
  await chooseFile("Upload map image");
  await expect(screen.getByLabel("Map image URL")).toHaveValue(/business-media\/.*\.webp/);
  await browser.locator('.add-section-row select').selectOption({ label: "Gallery" });
  await browser.locator('.live-items-heading button').tap();
  await screen.getByLabel("Gallery image 1 alt text").fill("Illustrative gallery photo");
  await chooseFile("Upload gallery image 1");
  await expect(screen.getByLabel("Gallery image 1 URL")).toHaveValue(/business-media\/.*\.webp/);
  await screen.getByRole("button", "Publish", { exact: true }).tap();
  await expect(browser.locator(".editor-save-status")).toHaveText("Published");
  await app.open(`/b/${slug}`);
  await expect(browser.locator('.gallery-photo img')).toHaveAttribute("alt", "Illustrative gallery photo");
  await expect(browser.locator('.hero-photo')).toHaveAttribute("loading", "eager");
  await expect(browser.locator('.gallery-photo img')).toHaveAttribute("loading", "lazy");
  expect(await browser.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  // Capture public screenshots in a separate anonymous test context; owner
  // credentials correctly prevent pixel capture in this authenticated test.
});

test("newer edits remain dirty during save; failures retry without losing input", async ({ app, screen, browser }) => {
  test.skip(process.env.E2E_ALLOW_MUTATIONS !== "true", "Requires an isolated mutation-enabled project");
  await app.open("/login");
  await screen.getByLabel("البريد الإلكتروني").fill(credentials.user("owner").username);
  await screen.getByLabel("كلمة المرور").fill(credentials.user("owner").password);
  await screen.getByRole("button", "دخول آمن").tap();
  await expect(browser).toHaveURL(/\/admin(?:\?.*)?$/);
  const fs = await import("node:fs/promises");
  const fixture = JSON.parse(await fs.readFile(".e2e/optimization-phase123/fixture.json", "utf8"));
  await app.open(`/admin/businesses/${fixture.businessId}`);
  await screen.getByLabel("Business name", { exact: true }).fill("Older saved revision");
  let release: () => void = () => {};
  const gate = new Promise<void>(resolve => release = resolve);
  await browser.route("**/admin/businesses/*", async route => { if (route.request.method === "POST") await gate; await route.continue(); });
  await screen.getByRole("button", "Save draft").tap();
  await expect(screen.getByRole("button", "Save draft")).toBeDisabled();
  await screen.getByLabel("Business name", { exact: true }).fill("Newer unsaved revision");
  release();
  await expect(browser.locator(".editor-save-status")).toContainText("Newer edits remain unsaved");
  await expect(screen.getByLabel("Business name", { exact: true })).toHaveValue("Newer unsaved revision");
  await expect(browser.locator('.editor-phone-screen h1')).toHaveText("Newer unsaved revision");
  await browser.evaluate(() => { window.confirm = () => false; return null; });
  await browser.locator('.editor-back').tap();
  await expect(browser).toHaveURL(`/admin/businesses/${fixture.businessId}`);
  const warns = await browser.evaluate(() => !window.dispatchEvent(new Event("beforeunload", { cancelable: true })));
  expect(warns).toBe(true);
  await browser.unroute("**/admin/businesses/*");
  await browser.route("**/admin/businesses/*", async route => { if (route.request.method === "POST") await route.fulfill({ status: 500, body: "Unavailable" }); else await route.continue(); });
  await screen.getByRole("button", "Save draft").tap();
  await expect(browser.locator('.visual-editor > [role="alert"]')).toContainText("edits are still here");
  await expect(screen.getByLabel("Business name", { exact: true })).toHaveValue("Newer unsaved revision");
  await browser.unroute("**/admin/businesses/*");
  await screen.getByRole("button", "Save draft").tap();
  await expect(browser.locator(".editor-save-status")).toHaveText("Draft saved");
  expect(await browser.evaluate(() => !window.dispatchEvent(new Event("beforeunload", { cancelable: true })))).toBe(false);
});
