import Link from "next/link";
export default function Home() {
  return <main>
    <header className="site-header"><div className="container header-row"><Link className="brand" href="/">Nex<span className="brand-mark">Tap</span></Link><nav className="nav"><a href="#how">كيف تعمل</a><a className="hide-small" href="#benefits">المميزات</a><Link href="/demo">صفحة تجريبية</Link><Link className="button secondary" href="/login">دخول المالك</Link></nav></div></header>
    <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">بطاقتك. قصتك. كل طرق التواصل.</span><h1>لمسة واحدة تفتح<br/>باب عملك.</h1><p>بطاقات NFC ورموز QR ذكية، مع صفحة أعمال سهلة التحديث تجمع روابطك وخدماتك في مكان واحد.</p><div className="hero-actions"><a className="button gold" href="https://wa.me/201000000000" target="_blank" rel="noreferrer">تواصل عبر واتساب</a><Link className="button secondary" href="/demo">شاهد صفحة تجريبية</Link></div></div><div className="device-card"><div className="device-screen"><div className="avatar-placeholder">ق</div><strong style={{fontSize:22}}>قهوة ومزاج</strong><p style={{color:"#777",margin:"3px 0 18px"}}>قهوة مختصة • القاهرة</p><span className="mini-action">اطلب عبر واتساب</span><span className="mini-action">قائمة المشروبات</span><span className="mini-action">موقعنا على الخريطة</span><span className="mini-action">تابعنا على إنستغرام</span></div></div></div></section>
    <section id="how" className="section"><div className="container"><div className="section-heading"><span className="eyebrow">ببساطة</span><h2>من البطاقة إلى عميلك في ثلاث خطوات</h2><p>تجربة سهلة لصاحب العمل، وسريعة لكل من يلمس البطاقة أو يمسح الرمز.</p></div><div className="steps"><article className="card"><div className="step-number">١</div><h3>أنشئ صفحتك</h3><p>أضف بيانات نشاطك وروابط التواصل والخدمات التي تريد عرضها.</p></article><article className="card"><div className="step-number">٢</div><h3>اربط بطاقتك</h3><p>كل بطاقة لها رابط دائم يمكن طباعته وكتابته على NFC مرة واحدة.</p></article><article className="card"><div className="step-number">٣</div><h3>شارك بلمسة</h3><p>حدّث محتوى صفحتك متى شئت من دون تغيير البطاقة المطبوعة.</p></article></div></div></section>
    <section id="benefits" className="section soft"><div className="container"><div className="section-heading"><span className="eyebrow">NexTap للأعمال</span><h2>كل ما يحتاجه عميلك، في صفحة واحدة</h2><p>تواصل مباشر ومعلومات واضحة على الهاتف، بالعربية والإنجليزية.</p></div><div className="features"><article className="card"><h3>روابطك مرتبة</h3><p>واتساب، شبكات التواصل، خرائط جوجل ووسائل الدفع الخارجية.</p></article><article className="card"><h3>تحديث فوري</h3><p>غيّر العروض أو مواعيد العمل مع بقاء رابط بطاقتك ثابتاً.</p></article><article className="card"><h3>بسيطة وآمنة</h3><p>صفحات سريعة وبطاقات برموز عشوائية لا تكشف بيانات داخلية.</p></article></div></div></section>
    <section className="section"><div className="container card" style={{textAlign:"center",padding:34}}><h2>ابدأ محادثة عن بطاقات نشاطك</h2><p className="muted">لا يوجد تسجيل ذاتي أو دفع إلكتروني على الموقع.</p><a className="button gold" href="https://wa.me/201000000000" target="_blank" rel="noreferrer">راسلنا على واتساب</a></div></section>
    <footer className="footer"><div className="container footer-row"><span className="brand">Nex<span className="brand-mark">Tap</span></span><span>بطاقات أعمال رقمية للأعمال المصرية</span><span>© NexTap</span></div></footer>
  </main>;
}